name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install dependencies
        run: npm install

      - name: Fix web folder
        run: sed -i 's/"webDir": "."/"webDir": "www"/' capacitor.config.json

      - name: Generate Android project
        run: npx cap add android

      - name: Sync Android project
        run: npx cap sync android

      - name: Make Gradle executable
        run: chmod +x android/gradlew

      - name: Build debug APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: 24-Math-Challenge-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
